Tweaked Discord album art implementation to make it more reliable. Closes #1136.
Taiko2k/TauonMusicBox pull request #1137
Opened 2024-04-26 05:50 UTC by G2-Games

It now uses both `release_group_id` and `release_id`, which makes it significantly more reliable.

2024-04-26 06:12 UTC, G2-Games commented
Closes issue #1136

2024-04-29 08:44 UTC, Taiko2k requested changes
I'm not sure the caching mechanism still works as intended with this revision.

The goal is that we want to minimize any unnecessary repeated calls. Caching both results and failures. To this end I created the dicts `pctl.album_mbid_cache` and `pctl.mbid_image_url_cache`. These can be changed as needed, though your change has implications for how the former of the two works. 

Could you revise the PR to ensure we don't make an API call with the same data twice. (within in the same session). You can revise the caching mechanism and associated variables as needed.

2024-04-29 08:44 UTC, Taiko2k commented on t_modules/t_main.py
> +    else:
This else path isn't cached?

2024-04-29 08:44 UTC, Taiko2k commented on t_modules/t_main.py
>                  pctl.album_mbid_cache[(artist, tr.album)] = mbid
Its no longer clear what this `mbid` named variable is or does, we should refactor this specific variable away.

2024-04-29 18:39 UTC, G2-Games commented
Good points, I will revise my implementation

2024-05-18 21:24 UTC, G2-Games commented
That should fix the caching issues I think

2024-05-19 07:28 UTC, merged